apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart-clocker.fullname" . }}
  labels:
    {{- include "chart-clocker.labels" . | nindent 4 }}
spec:
  podManagementPolicy: "Parallel"
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart-clocker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart-clocker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart-clocker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: configi
              mountPath: /app/config.json
              subPath: config.json
            {{- if .Values.mountVisits.enabled }}
            - name: logsy
              mountPath: /app/visits/
            {{- end}}
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: beautiful
                  key: token
          resources:
            requests:
              memory: "64M"
              cpu: "100m"
            limits:
              memory: "256M"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
              periodSeconds: 90
          readinessProbe:
            httpGet:
              path: /
              port: http
              periodSeconds: 90
          {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: configi
          configMap:
            name: some-config
        {{- if .Values.mountVisits.enabled}}
        - name: logsy
        {{- end }}
