version: "3"

networks:
    loki:

services:
    loki:
        image: grafana/loki:2.4.0
        volumes:
            - /mnt/c/Users/amira/logSystems/loki:/etc/loki
        ports:
            - "3100:3100"
        restart: unless-stopped
        command: -config.file=/etc/loki/loki-config.yml
        networks:
            - loki

    promtail:
        image: grafana/promtail:2.4.0
        volumes:
            - /var/log:/var/log
            - /mnt/c/Users/amira/logSystems/promtail:/etc/promtail
        restart: unless-stopped
        command: -config.file=/etc/promtail/promtail-config.yml
        networks:
            - loki

    grafana:
        image: grafana/grafana:latest
        user: "1000"
        volumes:
            - /mnt/c/Users/amira/logSystems/grafana:/var/lib/grafana
        ports:
            - "3000:3000"
        restart: unless-stopped
        networks:
            - loki