apiVersion: v1
kind: Service
metadata:
  name: exposer
  labels:
    app: clocker
spec:
  selector:
    app: clocker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer